fix: run npm audit fix; fix Jest CORS null forbidden
swagger-api/swagger-editor pull request #2236
Opened 2020-10-10 02:10 UTC by Fcmam5

### Description

- Attempt to fix #2223 by unsetting `XMLHttpRequest`.
- Run `npm audit fix` to fix some low severity warnings
- Fix a typo in README file
- Add .vscode to .gitignore

### Motivation and Context

Resolves  #2223

### How Has This Been Tested?

### Screenshots (if appropriate):

## Checklist

### My PR contains... 

- [x] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

2020-10-14 23:50 UTC, tim-lai requested changes
Thanks for the PR! Comments below:
- Changes to .gitignore is OK. Please provide as a separate PR.
- Changes to test/unit/setup.js is OK, though should add newline to EOF.
- Changes to README.md is outdated. Thanks for the catch though!
- Changes to package-lock.json is declined. I'm actively monitoring/waiting on node-fetch upstream effects.

2020-10-15 00:22 UTC, Fcmam5 commented
@tim-lai done, please can you check now?

2020-10-15 17:30 UTC, tim-lai approved these changes

2020-10-15 17:32 UTC, merged

2020-10-15 17:33 UTC, tim-lai commented
@Fcmam5 Merged! Thanks for the contribution!